### PR TITLE
Switch to magics-metview

### PR DESCRIPTION
**Pull request by dtip**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dtip** [comment]
@conda-forge-admin, please rerender

**Comment by dtip** [comment]
@conda-forge-admin, please rerender

**Comment by dtip** [comment]
Hi @ocefpaf I'm getting beaten here and now sure how to move forward :( Could you help at all?

The build is failing because it isn't linking with libblas properly. I've read https://conda-forge.org/docs/maintainer/knowledge_base.html#blas but it doesn't seem to have worked. I spent most of yesterday running local builds (using build_locally.py) with various permutations of libblas/liblapack deps added to the meta.yaml with no luck.

The problem seems to be that the library linker flags generated by cmake are incorrect. If I run the build natively on my machine the flags '-lblas -llapack' are included when building the offending library (libeckit_linalg.so), but when running the conda-forge docker build process these flags are missing. I have no idea what could cause this.

On my native machine I've installed all the build deps from conda, including libblas and liblapack. The versions of lblas and llapack which cmake links with are the versions from conda. I'm not sure why the environment is different when running on docker or why the linker flags generated by cmake would be different.

Do you have any ideas?

**Comment by ocefpaf** [comment]
hummmm. Blas and Linking cmake-problems, this sounds like something only @isuruf would know ;-p

(Sorry to ping you here to save us one more time @isuruf!)

**Comment by dtip** [comment]
@conda-forge-admin, please rerender.

**Comment by dtip** [comment]
@conda-forge-admin, please rerender.

**Comment by dtip** [comment]
@conda-forge-admin, please rerender.

**Comment by iainrussell** [comment]
Looks like blas and lapack were not necessary. I'll merge this now.

**Comment by dtip** [comment]
Of all the solutions this is definitely not what I was expecting! Thanks @iainrussell

**Comment by iainrussell** [comment]
Me neither, @dtip - just thought I'd try, in order to see what the original problem was that prompted you to add those libraries - the problem must have been something temporary! Now, if conda-forge can just finish the build without freezing and timing out... :)

**Pull request merged**
