### PR TITLE
Remove netcdf C++ library from requirements

### PR DESCRIPTION
**Pull request by iainrussell**
Checklist
* [ ] Used a fork of the feedstock to propose changes
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by dtip** [comment]
Hey @iainrussell , this looks like an rpcgen problem:
```
/bin/sh: /home/conda/feedstock_root/build_artifacts/metview_1564489400329/_build_env/x86_64-conda_cos6-linux-gnu/sysroot/usr/bin/rpcgen: /lib/ld-linux-x86-64.so.2: bad ELF interpreter: No such file or directory
```

I had a total nightmare with this, which is why I added https://github.com/conda-forge/metview-feedstock/blob/master/recipe/0002-Pass-CPP-to-rpcgen.patch and https://github.com/conda-forge/metview-feedstock/blob/master/recipe/0003-Pass-CPP-to-rpcgen.patch . It looks like they got removed from the most recent commit to master and it broke the build - what was the motivation there? New code made the patches stale perhaps?

I think your patch 0006 will replace my 0002, but you don't yet have one to replace 0003. Perhaps that's the problem here?

Side note - you have a handful of PRs open which do more-or-less the same thing by the looks of things. Can we close the others?

**Comment by iainrussell** [comment]
Hi @dtip, yes, this is very problematic! In fact, one of the patches was already incorporated into mars-client (0003) so it should not be needed, unless I missed something and it's not 100% the same. I should double-check that. Thanks for intervening! I was trying not to ask for help, but this has got me a bit stuck. And yes, I'll close the other PRs.

**Comment by dtip** [comment]
Hmm I'm not sure 0003 was included. I downloaded the source tarball from https://confluence.ecmwf.int/download/attachments/3964985/Metview-5.6.0-Source.tar.gz and checked `metview/src/libMars/CMakeLists.txt` . It's using RPCGEN_EXECUTABLE directly without first altering to work with conda. Patch 0003 fixed this file.

Likewise in `mars-client/src/CMakeLists.txt` it's using RPCGEN_EXECUTABLE directly, but your patch 0006 fixes this one.

My guess is `metview/src/libMars/CMakeLists.txt` is the culprit here! Good luck :)

**Comment by iainrussell** [comment]
In fact `metview/src/libMars/CMakeLists.txt`  is not used any more (I should just remove it - didn't realise it was still there), so it can't be that. We no longer duplicate the building of the Mars client. Back to it after a couple of days, so I'll try a couple more things!

**Comment by dtip** [comment]
I think this is probably dead but please re-open if not!

**Pull request closed without merging**
